CREATE TABLE USERS
(
   USERNAME varchar2(36) PRIMARY KEY NOT NULL,
   PASSWORD varchar2(36) NOT NULL,
   ROLE varchar2(36) NOT NULL,
   ENABLED decimal(1)
)
;
CREATE UNIQUE INDEX idx_users_nm ON USERS(USERNAME);


INSERT INTO USERS(USERNAME,PASSWORD,ROLE,ENABLED)
VALUES ('boaglio','boaglio','ROLE_USER',1);

commit;

